
```{r}
##Package installs
install.packages("xlsx")
install.packages("rJava")
install.packages("xlsxjars")
library(xlsx)
library(rJava)
library(xlsxjars)
```

```{r}
##Data Recode
Data <- BP_City_of_Fort_Worth_Benchmark_Survey_Data_v2_0_FINAL_190222
```

```{r}
##Change/Changes
##computing Change Variables
Data$Change <-
  (Data$Q_MAYOR_BAL2 - Data$Q_MAYOR_BAL1)
Data$Change1 <-
  (Data$Q_MAYOR_BAL3 - Data$Q_MAYOR_BAL2)
```


```{r}
##Variable codes
##Ballot Recode
Undecided <- Data [ which(Data$Q_MAYOR_BAL1 == 4), ]
Persuadable <- Data [ which(Data$Q_MAYOR_BAL1 %in% c(2:6)), ]
Undecided1 <- Data [ which(Data$Q_MAYOR_BAL2 == 4), ]
Persuadable1 <- Data [ which(Data$Q_MAYOR_BAL2 %in% c(2:6)), ]
##Gender
Men <- Data [ which(Data$R_GENDER == 1), ]
Women <- Data [ which(Data$R_GENDER == 2), ]
##Age
Age1844 <- Data [ which(Data$R_AGE == 1), ]
Age4564 <- Data [ which(Data$R_AGE == 2), ]
Age65 <- Data [ which(Data$R_AGE == 3), ]
##Gender x Age
Men1844 <- Data [ which(Data$R_GENAGE == 1), ]
Men4564 <- Data [ which(Data$R_GENAGE == 2), ]
Men65 <- Data [ which(Data$R_GENAGE == 3), ]
Women1844 <- Data [ which(Data$R_GENAGE == 4), ]
Women4564 <- Data [ which(Data$R_GENAGE == 5), ]
Women65 <- Data [ which(Data$R_GENAGE == 6), ]
##Race/Ethnicity
White <- Data [ which(Data$R_ETHNICITY == 1), ]
Hispanic <- Data [ which(Data$R_ETHNICITY == 2), ]
AfAmerican <- Data [ which(Data$R_ETHNICITY == 3), ]
##General Ideo
Conservative <- Data [ which(Data$R_IDEOLOGY == 1), ]
Moderate <- Data [ which(Data$R_IDEOLOGY == 2), ]
Liberal <- Data [ which(Data$R_IDEOLOGY == 3), ]
##Stated Party
Republican <- Data [ which(Data$R_PARTYID == 1), ]
Independent <- Data [ which(Data$R_PARTYID == 2), ]
Democrat <- Data [ which(Data$R_PARTYID == 3), ]
##Region
CentralFW <- Data [ which(Data$R_REGION == 1), ]
Outskirts <- Data [ which(Data$R_REGION == 2), ]
SouthFW <- Data [ which(Data$R_REGION == 3), ]
EastFW <- Data [ which(Data$R_REGION == 4), ]
```

```{r}
##Client Positive Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Data)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Data) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Data) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Data)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Data) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Overall")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Overall")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Overall")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Overall")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Ballot Regressions
##Undecided Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Undecided) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Undecided)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Undecided)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Undecided)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Undecided) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Undecided) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Undecided) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Undecided)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Undecided) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Undecided)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Undecided) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Undecided) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Undecided)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Undecided) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Undecided)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Undecided")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Undecided")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Undecided")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Undecided")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Undecided")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Undecided")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Undecided")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Undecided")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Undecided")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Undecided")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Undecided")
UndecidedReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Persuadable Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Persuadable) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Persuadable)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Persuadable)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Persuadable)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Persuadable) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Persuadable) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Persuadable) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Persuadable)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Persuadable) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Persuadable)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Persuadable) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Persuadable) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Persuadable)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Persuadable) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Persuadable)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Persuadable")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Persuadable")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Persuadable")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Persuadable")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Persuadable")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Persuadable")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Persuadable")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Persuadable")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Persuadable")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Persuadable")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Persuadable")
PersuadableReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Men)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Men) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Men) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Men)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Men) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Men")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Men")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Men")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Men")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Women)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Women) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Women) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Women)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Women) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Women")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Women")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Women")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Women")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Age1844)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Age1844) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Age1844) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Age1844)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Age1844) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Age1844")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Age1844")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Age1844")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Age1844")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Age4564)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Age4564) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Age4564) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Age4564)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Age4564) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Age4564")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Age4564")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Age4564")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Age4564")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Age65)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Age65) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Age65) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Age65)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Age65) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Age65")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Age65")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Age65")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Age65")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Men1844)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Men1844) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Men1844) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Men1844)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Men1844) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Men1844")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Men1844")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Men1844")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Men1844")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Men4564)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Men4564) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Men4564) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Men4564)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Men4564) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Men4564")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Men4564")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Men4564")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Men4564")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Men65)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Men65) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Men65) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Men65)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Men65) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Men65")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Men65")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Men65")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Men65")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Women1844)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Women1844) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Women1844) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Women1844)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Women1844) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Women1844")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Women1844")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Women1844")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Women1844")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Women4564)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Women4564) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Women4564) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Women4564)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Women4564) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Women4564")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Women4564")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Women4564")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Women4564")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Women65)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Women65) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Women65) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Women65)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Women65) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Women65")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Women65")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Women65")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Women65")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = White)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = White) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = White) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = White)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = White) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("White")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("White")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("White")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("White")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Hispanic)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Hispanic) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Hispanic) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Hispanic)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Hispanic) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Hispanic")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Hispanic")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Hispanic")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Hispanic")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##African American Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = AfAmerican) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = AfAmerican)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = AfAmerican)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = AfAmerican)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = AfAmerican) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = AfAmerican) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = AfAmerican) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = AfAmerican)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = AfAmerican) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = AfAmerican)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = AfAmerican) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = AfAmerican) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = AfAmerican)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = AfAmerican) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = AfAmerican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("AfAmerican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("AfAmerican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("AfAmerican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("AfAmerican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("AfAmerican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("AfAmerican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("AfAmerican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("AfAmerican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("AfAmerican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("AfAmerican")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("AfAmerican")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("AfAmerican")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("AfAmerican")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("AfAmerican")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("AfAmerican")
AfAmericanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Conservative)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Conservative) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Conservative) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Conservative)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Conservative) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Conservative")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Conservative")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Conservative")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Conservative")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Moderate)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Moderate) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Moderate) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Moderate)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Moderate) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Moderate")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Moderate")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Moderate")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Moderate")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Liberal)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Liberal) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Liberal) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Liberal)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Liberal) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Liberal")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Liberal")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Liberal")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Liberal")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Republican) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Republican)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Republican)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Republican)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Republican) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Republican) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Republican) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Republican)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Republican) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Republican)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Republican) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Republican) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Republican)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Republican) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Republican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Republican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Republican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Republican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Republican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Republican")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Republican")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Republican")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Republican")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Republican")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Independent Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Independent) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Independent)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Independent)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Independent)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Independent) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Independent) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Independent) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Independent)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Independent) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Independent)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Independent) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Independent) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Independent)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Independent) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Independent")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Independent")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Independent")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Independent")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Independent")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Independent")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Independent")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Independent")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Independent")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Independent")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Democrat Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Democrat) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Democrat)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Democrat)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Democrat)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Democrat) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Democrat) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Democrat) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Democrat)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Democrat) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Democrat)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Democrat) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Democrat) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Democrat)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Democrat) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Democrat")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Democrat")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Democrat")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Democrat")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Democrat")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Democrat")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Democrat")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Democrat")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Democrat")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Democrat")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

#Region Regressions
##Central FW Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = CentralFW) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = CentralFW)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = CentralFW)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = CentralFW)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = CentralFW) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = CentralFW) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = CentralFW) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = CentralFW)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = CentralFW) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = CentralFW)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = CentralFW) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = CentralFW) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = CentralFW)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = CentralFW) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = CentralFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("CentralFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("CentralFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("CentralFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("CentralFW")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("CentralFW")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("CentralFW")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("CentralFW")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("CentralFW")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("CentralFW")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("CentralFW")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("CentralFW")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("CentralFW")
B113 <- data.frame(coefficients(fit13))
colnames(B13) <- ("CentralFW")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("CentralFW")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("CentralFW")
CentralFWReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##Outskirts Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = Outskirts) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = Outskirts)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = Outskirts)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = Outskirts)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = Outskirts) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = Outskirts) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = Outskirts) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = Outskirts)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = Outskirts) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = Outskirts)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = Outskirts) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = Outskirts) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = Outskirts)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = Outskirts) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = Outskirts)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Outskirts")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Outskirts")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Outskirts")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Outskirts")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Outskirts")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Outskirts")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Outskirts")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Outskirts")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Outskirts")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Outskirts")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("Outskirts")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("Outskirts")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("Outskirts")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("Outskirts")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("Outskirts")
OutskirtsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##SouthFW Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = SouthFW) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = SouthFW)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = SouthFW)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = SouthFW)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = SouthFW) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = SouthFW) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = SouthFW) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = SouthFW)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = SouthFW) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = SouthFW)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = SouthFW) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = SouthFW) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = SouthFW)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = SouthFW) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = SouthFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SouthFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SouthFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SouthFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SouthFW")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SouthFW")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SouthFW")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SouthFW")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SouthFW")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SouthFW")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SouthFW")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("SouthFW")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("SouthFW")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("SouthFW")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("SouthFW")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("SouthFW")
SouthFWReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

##EastFW Regression with Weight
fit1 <- lm(Change ~ HRD_BP_POS_14, weights = Weight, data = EastFW) 
fit2 <- lm(Change ~ HRD_BP_POS_15, weights = Weight, data = EastFW)
fit3 <- lm(Change ~ HRD_BP_POS_16, weights = Weight, data = EastFW)
fit4 <- lm(Change ~ HRD_BP_POS_17, weights = Weight, data = EastFW)
fit5 <- lm(Change ~ HRD_BP_POS_18, weights = Weight, data = EastFW) 
fit6 <- lm(Change ~ HRD_BP_POS_19, weights = Weight, data = EastFW) 
fit7 <- lm(Change ~ HRD_BP_POS_20, weights = Weight, data = EastFW) 
fit8 <- lm(Change ~ HRD_BP_POS_21, weights = Weight, data = EastFW)
fit9 <- lm(Change ~ HRD_BP_POS_22, weights = Weight, data = EastFW) 
fit10 <- lm(Change ~ HRD_BP_POS_23, weights = Weight, data = EastFW)
fit11 <- lm(Change ~ HRD_BP_POS_24, weights = Weight, data = EastFW) 
fit12 <- lm(Change ~ HRD_BP_POS_25, weights = Weight, data = EastFW) 
fit13 <- lm(Change ~ HRD_BP_POS_26, weights = Weight, data = EastFW)
fit14 <- lm(Change ~ HRD_BP_POS_27, weights = Weight, data = EastFW) 
fit15 <- lm(Change ~ HRD_BP_POS_28, weights = Weight, data = EastFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("EastFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("EastFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("EastFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("EastFW")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("EastFW")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("EastFW")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("EastFW")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("EastFW")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("EastFW")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("EastFW")
B11 <- data.frame(coefficients(fit11))
colnames(B11) <- ("EastFW")
B12 <- data.frame(coefficients(fit12))
colnames(B12) <- ("EastFW")
B13 <- data.frame(coefficients(fit13))
colnames(B13) <- ("EastFW")
B14 <- data.frame(coefficients(fit14))
colnames(B14) <- ("EastFW")
B15 <- data.frame(coefficients(fit15))
colnames(B15) <- ("EastFW")
EastFWReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15)

ClientPosReg <- cbind(OverallReg, UndecidedReg, PersuadableReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, AfAmericanReg, ConservativeReg, ModerateReg, LiberalReg, RepublicanReg, IndependentReg, DemocratReg, CentralFWReg, OutskirtsReg, SouthFWReg, EastFWReg)
write.csv(ClientPosReg, file ="ClientPosReg.csv")
##Possibly combine into one excel file with:
write.xlsx(ClientPosReg, file ="BP_CityofFW_Mayor.xlsx", sheetName = "ClientPosReg", append = FALSE)
```

```{r}
##Opponent 1 Negative Messaging
##Topline Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Data) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Data)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Data)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4)

##Ballot Regressions
##Undecided1 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Undecided1) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Undecided1)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Undecided1)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Undecided1)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided1")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided1")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided1")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided1")
Undecided1Reg <- rbind(B1,B2,B3,B4)

##Persuadable1 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Persuadable1) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Persuadable1)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Persuadable1)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Persuadable1)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable1")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable1")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable1")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable1")
Persuadable1Reg <- rbind(B1,B2,B3,B4)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Men) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Men)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Men)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4)

##Women Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Women) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Women)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Women)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Age1844) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Age1844)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Age1844)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4)

##Age4564 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Age4564) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Age4564)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Age4564)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4)

##Age65 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Age65) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Age65)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Age65)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Men1844) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Men1844)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Men1844)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4)

##Men4564 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Men4564) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Men4564)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Men4564)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4)

##Men65 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Men65) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Men65)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Men65)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4)

##Women1844 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Women1844) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Women1844)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Women1844)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4)

##Women4564 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Women4564) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Women4564)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Women4564)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4)

##Women65 Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Women65) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Women65)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Women65)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = White) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = White)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = White)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4)

##Hispanic Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Hispanic) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Hispanic)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Hispanic)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4)

##African American Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = AfAmerican) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = AfAmerican)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = AfAmerican)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = AfAmerican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("AfAmerican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("AfAmerican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("AfAmerican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("AfAmerican")
AfAmericanReg <- rbind(B1,B2,B3,B4)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Conservative) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Conservative)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Conservative)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4)

##Moderate Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Moderate) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Moderate)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Moderate)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4)

##Liberal Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Liberal) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Liberal)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Liberal)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Republican) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Republican)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Republican)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4)

##Independent Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Independent) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Independent)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Independent)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4)

##Democrat Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Democrat) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Democrat)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Democrat)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4)

#Region Regressions
##Central FW Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = CentralFW) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = CentralFW)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = CentralFW)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = CentralFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("CentralFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("CentralFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("CentralFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("CentralFW")
CentralFWReg <- rbind(B1,B2,B3,B4)

##Outskirts Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = Outskirts) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = Outskirts)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = Outskirts)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = Outskirts)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Outskirts")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Outskirts")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Outskirts")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Outskirts")
OutskirtsReg <- rbind(B1,B2,B3,B4)

##SouthFW Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = SouthFW) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = SouthFW)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = SouthFW)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = SouthFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SouthFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SouthFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SouthFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SouthFW")
SouthFWReg <- rbind(B1,B2,B3,B4)

##EastFW Regression with Weight
fit1 <- lm(Change1 ~ HRD_DP_NEG_30, weights = Weight, data = EastFW) 
fit2 <- lm(Change1 ~ HRD_DP_NEG_31, weights = Weight, data = EastFW)
fit3 <- lm(Change1 ~ HRD_DP_NEG_32, weights = Weight, data = EastFW)
fit4 <- lm(Change1 ~ HRD_DP_NEG_33, weights = Weight, data = EastFW)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("EastFW")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("EastFW")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("EastFW")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("EastFW")
EastFWReg <- rbind(B1,B2,B3,B4)

Cand1NegReg <- cbind(OverallReg, Undecided1Reg, Persuadable1Reg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, AfAmericanReg, ConservativeReg, ModerateReg, LiberalReg, RepublicanReg, IndependentReg, DemocratReg, CentralFWReg, OutskirtsReg, SouthFWReg, EastFWReg)

write.csv(Cand1NegReg, file ="Cand1NegReg.csv")
##Possibly combine into one excel file with:
write.xlsx(Cand1NegReg, file ="BP_CityofFW_Mayor.xlsx", sheetName = "Cand1NegReg", append = TRUE)
```


