
```{r}
##Package installs
install.packages("xlsx")
install.packages("rJava")
install.packages("xlsxjars")
library(xlsx)
library(rJava)
library(xlsxjars)
```

```{r}
##Variable codes
Data <- ACC_Amarillo_n300_1_1_DDWRKG
##Ballot Recode
Undecided <- Data [ which(Data$Q_SuppOppo_Initial == 3), ]
Persuadable <- Data [ which(Data$Q_SuppOppo_Initial %in% c(2:4)), ]
##Gender
Men <- Data [ which(Data$R_GENDER == 1), ]
Women <- Data [ which(Data$R_GENDER == 2), ]
##Age
Age1844 <- Data [ which(Data$R_AGE == 1), ]
Age4564 <- Data [ which(Data$R_AGE == 2), ]
Age65 <- Data [ which(Data$R_AGE == 3), ]
##Gender x Age
Men1844 <- Data [ which(Data$R_GENAGE == 1), ]
Men4564 <- Data [ which(Data$R_GENAGE == 2), ]
Men65 <- Data [ which(Data$R_GENAGE == 3), ]
Women1844 <- Data [ which(Data$R_GENAGE == 4), ]
Women4564 <- Data [ which(Data$R_GENAGE == 5), ]
Women65 <- Data [ which(Data$R_GENAGE == 6), ]
##Race/Ethnicity
White <- Data [ which(Data$R_ETHNICITY == 1), ]
Hispanic <- Data [ which(Data$R_ETHNICITY == 2), ]
##General Ideo
Conservative <- Data [ which(Data$R_Ideology == 1), ]
Moderate <- Data [ which(Data$R_Ideology == 2), ]
Liberal <- Data [ which(Data$R_Ideology == 3), ]
##Primary Ideo
VeryCons <- Data [ which(Data$Q_Ideology == 6), ]
SmwtCons <- Data [ which(Data$Q_Ideology == 5), ]
ModLib <- Data [ which(Data$Q_Ideology %in% c(1:3)), ]
##Stated Party
Republican <- Data [ which(Data$R_PartyID == 1), ]
Independent <- Data [ which(Data$R_PartyID == 2), ]
Democrat <- Data [ which(Data$R_PartyID == 3), ]
##Region
Potter <- Data [ which(Data$R_REGION1 == 1), ]
Randall <- Data [ which(Data$R_REGION1 == 2), ]
##Project Specific Codes
SixtyMil <- Data [ which(Data$QSplitABC == 1), ]
SevenFiveMil <- Data [ which(Data$QSplitABC == 2), ]
NinteyMil <- Data [ which(Data$QSplitABC == 3), ]
HasKids <- Data [ which(Data$Q_Child == 1), ]
NoKids <- Data [ which(Data$Q_Child == 2), ]

```

```{r}
##Change/Changes
##computing Change Variables
Data$Change <-
  (Data$Q_SuppOppo_InF - Data$Q_SuppOppo_Initial)

```

```{r}
##Client Positive Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ballot Regressions
##Undecided Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Undecided) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Undecided)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Undecided)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Undecided)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Undecided) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Undecided) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Undecided) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Undecided)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Undecided) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Undecided)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Undecided")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Undecided")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Undecided")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Undecided")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Undecided")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Undecided")
UndecidedReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Persuadable Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Persuadable) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Persuadable)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Persuadable)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Persuadable)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Persuadable) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Persuadable) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Persuadable) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Persuadable)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Persuadable) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Persuadable)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Persuadable")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Persuadable")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Persuadable")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Persuadable")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Persuadable")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Persuadable")
PersuadableReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Primary Ideo Regressions
##Very Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = VeryCons) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = VeryCons)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = VeryCons)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = VeryCons)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = VeryCons) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = VeryCons) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = VeryCons) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = VeryCons)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = VeryCons) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = VeryCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("VeryCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("VeryCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("VeryCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("VeryCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("VeryCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("VeryCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("VeryCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("VeryCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("VeryCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("VeryCons")
VeryConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Somewhat Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = SmwtCons) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = SmwtCons)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = SmwtCons)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = SmwtCons)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = SmwtCons) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = SmwtCons) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = SmwtCons) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = SmwtCons)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = SmwtCons) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = SmwtCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SmwtCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SmwtCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SmwtCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SmwtCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SmwtCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SmwtCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SmwtCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SmwtCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SmwtCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SmwtCons")
SmwtConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Mod/Lib Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = ModLib) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = ModLib)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = ModLib)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = ModLib)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = ModLib) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = ModLib) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = ModLib) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = ModLib)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = ModLib) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = ModLib)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("ModLib")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("ModLib")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("ModLib")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("ModLib")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("ModLib")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("ModLib")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("ModLib")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("ModLib")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("ModLib")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("ModLib")
ModLibReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Republican) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Republican)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Republican)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Republican)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Republican) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Republican) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Republican) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Republican)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Republican) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Republican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Republican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Republican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Republican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Republican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Independent Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Independent) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Independent)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Independent)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Independent)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Independent) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Independent) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Independent) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Independent)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Independent) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Independent")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Independent")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Independent")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Independent")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Independent")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Democrat Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Democrat) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Democrat)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Democrat)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Democrat)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Democrat) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Democrat) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Democrat) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Democrat)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Democrat) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Democrat")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Democrat")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Democrat")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Democrat")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Democrat")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

#Region Regressions
##Potter Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Potter) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Potter)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Potter)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Potter)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Potter) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Potter) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Potter) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Potter)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Potter) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Potter)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Potter")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Potter")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Potter")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Potter")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Potter")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Potter")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Potter")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Potter")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Potter")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Potter")
PotterReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Randall Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = Randall) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = Randall)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = Randall)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = Randall)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = Randall) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = Randall) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = Randall) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = Randall)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = Randall) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = Randall)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Randall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Randall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Randall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Randall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Randall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Randall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Randall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Randall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Randall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Randall")
RandallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Project Specific Regressions
##Sixty Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = SixtyMil) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = SixtyMil)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = SixtyMil)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = SixtyMil)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = SixtyMil) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = SixtyMil) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = SixtyMil) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = SixtyMil)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = SixtyMil) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = SixtyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SixtyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SixtyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SixtyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SixtyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SixtyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SixtyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SixtyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SixtyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SixtyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SixtyMil")
SixtyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Seventy five Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = SevenFiveMil) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = SevenFiveMil)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = SevenFiveMil)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = SevenFiveMil)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = SevenFiveMil) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = SevenFiveMil) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = SevenFiveMil) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = SevenFiveMil)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = SevenFiveMil) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = SevenFiveMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SevenFiveMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SevenFiveMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SevenFiveMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SevenFiveMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SevenFiveMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SevenFiveMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SevenFiveMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SevenFiveMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SevenFiveMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SevenFiveMil")
SevenFiveMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ninety Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = NinteyMil) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = NinteyMil)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = NinteyMil)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = NinteyMil)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = NinteyMil) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = NinteyMil) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = NinteyMil) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = NinteyMil)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = NinteyMil) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = NinteyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NinteyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NinteyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NinteyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NinteyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NinteyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NinteyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NinteyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NinteyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NinteyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NinteyMil")
NinteyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Has Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = HasKids) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = HasKids)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = HasKids)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = HasKids)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = HasKids) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = HasKids) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = HasKids) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = HasKids)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = HasKids) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = HasKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("HasKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("HasKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("HasKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("HasKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("HasKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("HasKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("HasKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("HasKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("HasKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("HasKids")
HasKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##No Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_1, weights = Weight, data = NoKids) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_2, weights = Weight, data = NoKids)
fit3 <- lm(Change ~ HRD_CLIENT_POS_3, weights = Weight, data = NoKids)
fit4 <- lm(Change ~ HRD_CLIENT_POS_4, weights = Weight, data = NoKids)
fit5 <- lm(Change ~ HRD_CLIENT_POS_5, weights = Weight, data = NoKids) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_6, weights = Weight, data = NoKids) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_7, weights = Weight, data = NoKids) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_8, weights = Weight, data = NoKids)
fit9 <- lm(Change ~ HRD_CLIENT_POS_9, weights = Weight, data = NoKids) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_10, weights = Weight, data = NoKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NoKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NoKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NoKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NoKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NoKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NoKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NoKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NoKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NoKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NoKids")
NoKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

ClientPosReg <- cbind(OverallReg, UndecidedReg, PersuadableReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, ConservativeReg, VeryConsReg, SmwtConsReg, ModerateReg, LiberalReg, ModLibReg, RepublicanReg, IndependentReg, DemocratReg, PotterReg, RandallReg, SixtyMilReg, SevenFiveMilReg, NinteyMil, HasKidsReg, NoKidsReg)
write.csv(ClientPosReg, file ="ClientPosReg.csv")
##Possibly combine into one excel file with:
write.xlsx(ClientPosReg, file ="Region_Race.xlsx", sheetName = "ClientPosReg", append = FALSE)
```

```{r}
##Opponent 1 Negative Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ballot Regressions
##Undecided Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Undecided) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Undecided)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Undecided)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Undecided)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Undecided) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Undecided) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Undecided) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Undecided)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Undecided) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Undecided)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Undecided")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Undecided")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Undecided")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Undecided")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Undecided")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Undecided")
UndecidedReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Persuadable Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Persuadable) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Persuadable)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Persuadable)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Persuadable)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Persuadable) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Persuadable) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Persuadable) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Persuadable)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Persuadable) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Persuadable)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Persuadable")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Persuadable")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Persuadable")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Persuadable")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Persuadable")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Persuadable")
PersuadableReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Primary Ideo Regressions
##Very Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = VeryCons) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = VeryCons)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = VeryCons)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = VeryCons)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = VeryCons) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = VeryCons) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = VeryCons) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = VeryCons)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = VeryCons) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = VeryCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("VeryCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("VeryCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("VeryCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("VeryCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("VeryCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("VeryCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("VeryCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("VeryCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("VeryCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("VeryCons")
VeryConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Somewhat Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = SmwtCons) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = SmwtCons)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = SmwtCons)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = SmwtCons)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = SmwtCons) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = SmwtCons) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = SmwtCons) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = SmwtCons)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = SmwtCons) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = SmwtCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SmwtCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SmwtCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SmwtCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SmwtCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SmwtCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SmwtCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SmwtCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SmwtCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SmwtCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SmwtCons")
SmwtConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Mod/Lib Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = ModLib) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = ModLib)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = ModLib)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = ModLib)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = ModLib) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = ModLib) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = ModLib) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = ModLib)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = ModLib) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = ModLib)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("ModLib")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("ModLib")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("ModLib")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("ModLib")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("ModLib")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("ModLib")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("ModLib")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("ModLib")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("ModLib")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("ModLib")
ModLibReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Republican) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Republican)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Republican)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Republican)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Republican) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Republican) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Republican) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Republican)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Republican) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Republican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Republican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Republican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Republican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Republican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Independent Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Independent) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Independent)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Independent)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Independent)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Independent) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Independent) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Independent) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Independent)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Independent) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Independent")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Independent")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Independent")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Independent")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Independent")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Democrat Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Democrat) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Democrat)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Democrat)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Democrat)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Democrat) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Democrat) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Democrat) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Democrat)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Democrat) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Democrat")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Democrat")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Democrat")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Democrat")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Democrat")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Region Regressions
##Potter Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Potter) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Potter)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Potter)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Potter)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Potter) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Potter) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Potter) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Potter)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Potter) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Potter)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Potter")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Potter")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Potter")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Potter")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Potter")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Potter")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Potter")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Potter")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Potter")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Potter")
PotterReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Randall Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = Randall) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = Randall)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = Randall)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = Randall)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = Randall) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = Randall) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = Randall) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = Randall)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = Randall) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = Randall)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Randall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Randall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Randall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Randall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Randall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Randall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Randall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Randall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Randall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Randall")
RandallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Project Specific Regressions
##Sixty Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = SixtyMil) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = SixtyMil)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = SixtyMil)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = SixtyMil)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = SixtyMil) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = SixtyMil) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = SixtyMil) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = SixtyMil)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = SixtyMil) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = SixtyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SixtyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SixtyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SixtyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SixtyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SixtyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SixtyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SixtyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SixtyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SixtyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SixtyMil")
SixtyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Seventy five Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = SevenFiveMil) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = SevenFiveMil)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = SevenFiveMil)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = SevenFiveMil)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = SevenFiveMil) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = SevenFiveMil) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = SevenFiveMil) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = SevenFiveMil)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = SevenFiveMil) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = SevenFiveMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SevenFiveMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SevenFiveMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SevenFiveMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SevenFiveMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SevenFiveMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SevenFiveMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SevenFiveMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SevenFiveMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SevenFiveMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SevenFiveMil")
SevenFiveMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ninety Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = NinteyMil) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = NinteyMil)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = NinteyMil)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = NinteyMil)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = NinteyMil) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = NinteyMil) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = NinteyMil) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = NinteyMil)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = NinteyMil) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = NinteyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NinteyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NinteyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NinteyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NinteyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NinteyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NinteyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NinteyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NinteyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NinteyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NinteyMil")
NinteyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Has Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = HasKids) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = HasKids)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = HasKids)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = HasKids)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = HasKids) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = HasKids) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = HasKids) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = HasKids)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = HasKids) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = HasKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("HasKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("HasKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("HasKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("HasKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("HasKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("HasKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("HasKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("HasKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("HasKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("HasKids")
HasKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##No Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_NEG_1, weights = Weight, data = NoKids) 
fit2 <- lm(Change ~ HRD_CAND1_NEG_2, weights = Weight, data = NoKids)
fit3 <- lm(Change ~ HRD_CAND1_NEG_3, weights = Weight, data = NoKids)
fit4 <- lm(Change ~ HRD_CAND1_NEG_4, weights = Weight, data = NoKids)
fit5 <- lm(Change ~ HRD_CAND1_NEG_5, weights = Weight, data = NoKids) 
fit6 <- lm(Change ~ HRD_CAND1_NEG_6, weights = Weight, data = NoKids) 
fit7 <- lm(Change ~ HRD_CAND1_NEG_7, weights = Weight, data = NoKids) 
fit8 <- lm(Change ~ HRD_CAND1_NEG_8, weights = Weight, data = NoKids)
fit9 <- lm(Change ~ HRD_CAND1_NEG_9, weights = Weight, data = NoKids) 
fit10 <- lm(Change ~ HRD_CAND1_NEG_10, weights = Weight, data = NoKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NoKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NoKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NoKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NoKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NoKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NoKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NoKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NoKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NoKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NoKids")
NoKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

Cand1NegReg <- cbind(OverallReg, UndecidedReg, PersuadableReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, ConservativeReg, VeryConsReg, SmwtConsReg, ModerateReg, LiberalReg, ModLibReg, RepublicanReg, IndependentReg, DemocratReg, PotterReg, RandallReg, SixtyMilReg, SevenFiveMilReg, NinteyMil, HasKidsReg, NoKidsReg)
write.csv(Cand1NegReg, file ="Cand1NegReg.csv")
##Possibly combine into one excel file with:
write.xlsx(Cand1NegReg, file ="Region_Race.xlsx", sheetName = "Cand1NegReg", append = TRUE)
```


```{r}
##Client Negative Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ballot Regressions
##Undecided Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Undecided) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Undecided)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Undecided)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Undecided)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Undecided) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Undecided) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Undecided) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Undecided)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Undecided) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Undecided)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Undecided")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Undecided")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Undecided")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Undecided")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Undecided")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Undecided")
UndecidedReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Persuadable Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Persuadable) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Persuadable)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Persuadable)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Persuadable)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Persuadable) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Persuadable) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Persuadable) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Persuadable)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Persuadable) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Persuadable)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Persuadable")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Persuadable")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Persuadable")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Persuadable")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Persuadable")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Persuadable")
PersuadableReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Primary Ideo Regressions
##Very Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = VeryCons) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = VeryCons)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = VeryCons)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = VeryCons)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = VeryCons) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = VeryCons) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = VeryCons) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = VeryCons)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = VeryCons) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = VeryCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("VeryCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("VeryCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("VeryCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("VeryCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("VeryCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("VeryCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("VeryCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("VeryCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("VeryCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("VeryCons")
VeryConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Somewhat Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = SmwtCons) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = SmwtCons)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = SmwtCons)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = SmwtCons)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = SmwtCons) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = SmwtCons) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = SmwtCons) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = SmwtCons)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = SmwtCons) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = SmwtCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SmwtCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SmwtCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SmwtCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SmwtCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SmwtCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SmwtCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SmwtCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SmwtCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SmwtCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SmwtCons")
SmwtConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Mod/Lib Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = ModLib) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = ModLib)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = ModLib)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = ModLib)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = ModLib) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = ModLib) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = ModLib) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = ModLib)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = ModLib) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = ModLib)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("ModLib")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("ModLib")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("ModLib")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("ModLib")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("ModLib")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("ModLib")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("ModLib")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("ModLib")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("ModLib")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("ModLib")
ModLibReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Republican) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Republican)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Republican)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Republican)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Republican) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Republican) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Republican) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Republican)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Republican) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Republican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Republican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Republican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Republican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Republican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Independent Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Independent) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Independent)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Independent)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Independent)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Independent) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Independent) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Independent) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Independent)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Independent) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Independent")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Independent")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Independent")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Independent")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Independent")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Democrat Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Democrat) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Democrat)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Democrat)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Democrat)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Democrat) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Democrat) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Democrat) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Democrat)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Democrat) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Democrat")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Democrat")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Democrat")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Democrat")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Democrat")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Region Regressions
##Potter Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Potter) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Potter)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Potter)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Potter)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Potter) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Potter) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Potter) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Potter)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Potter) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Potter)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Potter")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Potter")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Potter")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Potter")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Potter")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Potter")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Potter")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Potter")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Potter")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Potter")
PotterReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Randall Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = Randall) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = Randall)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = Randall)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = Randall)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = Randall) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = Randall) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = Randall) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = Randall)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = Randall) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = Randall)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Randall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Randall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Randall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Randall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Randall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Randall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Randall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Randall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Randall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Randall")
RandallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Project Specific Regressions
##Sixty Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = SixtyMil) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = SixtyMil)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = SixtyMil)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = SixtyMil)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = SixtyMil) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = SixtyMil) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = SixtyMil) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = SixtyMil)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = SixtyMil) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = SixtyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SixtyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SixtyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SixtyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SixtyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SixtyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SixtyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SixtyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SixtyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SixtyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SixtyMil")
SixtyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Seventy five Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = SevenFiveMil) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = SevenFiveMil)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = SevenFiveMil)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = SevenFiveMil)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = SevenFiveMil) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = SevenFiveMil) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = SevenFiveMil) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = SevenFiveMil)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = SevenFiveMil) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = SevenFiveMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SevenFiveMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SevenFiveMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SevenFiveMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SevenFiveMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SevenFiveMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SevenFiveMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SevenFiveMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SevenFiveMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SevenFiveMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SevenFiveMil")
SevenFiveMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ninety Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = NinteyMil) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = NinteyMil)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = NinteyMil)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = NinteyMil)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = NinteyMil) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = NinteyMil) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = NinteyMil) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = NinteyMil)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = NinteyMil) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = NinteyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NinteyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NinteyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NinteyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NinteyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NinteyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NinteyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NinteyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NinteyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NinteyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NinteyMil")
NinteyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Has Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = HasKids) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = HasKids)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = HasKids)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = HasKids)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = HasKids) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = HasKids) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = HasKids) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = HasKids)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = HasKids) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = HasKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("HasKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("HasKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("HasKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("HasKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("HasKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("HasKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("HasKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("HasKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("HasKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("HasKids")
HasKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##No Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_NEG_1, weights = Weight, data = NoKids) 
fit2 <- lm(Change ~ HRD_CLIENT_NEG_2, weights = Weight, data = NoKids)
fit3 <- lm(Change ~ HRD_CLIENT_NEG_3, weights = Weight, data = NoKids)
fit4 <- lm(Change ~ HRD_CLIENT_NEG_4, weights = Weight, data = NoKids)
fit5 <- lm(Change ~ HRD_CLIENT_NEG_5, weights = Weight, data = NoKids) 
fit6 <- lm(Change ~ HRD_CLIENT_NEG_6, weights = Weight, data = NoKids) 
fit7 <- lm(Change ~ HRD_CLIENT_NEG_7, weights = Weight, data = NoKids) 
fit8 <- lm(Change ~ HRD_CLIENT_NEG_8, weights = Weight, data = NoKids)
fit9 <- lm(Change ~ HRD_CLIENT_NEG_9, weights = Weight, data = NoKids) 
fit10 <- lm(Change ~ HRD_CLIENT_NEG_10, weights = Weight, data = NoKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NoKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NoKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NoKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NoKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NoKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NoKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NoKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NoKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NoKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NoKids")
NoKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

ClientNegReg <- cbind(OverallReg, UndecidedReg, PersuadableReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, ConservativeReg, VeryConsReg, SmwtConsReg, ModerateReg, LiberalReg, ModLibReg, RepublicanReg, IndependentReg, DemocratReg, PotterReg, RandallReg, SixtyMilReg, SevenFiveMilReg, NinteyMil, HasKidsReg, NoKidsReg)
write.csv(ClientNegReg, file ="ClientNegReg.csv")
##Possibly combine into one excel file with:
write.xlsx(ClientNegReg, file ="Region_Race.xlsx", sheetName = "ClientNegReg", append = TRUE)
```

```{r}
##Opponent 1 Positive Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ballot Regressions
##Undecided Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Undecided) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Undecided)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Undecided)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Undecided)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Undecided) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Undecided) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Undecided) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Undecided)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Undecided) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Undecided)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Undecided")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Undecided")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Undecided")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Undecided")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Undecided")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Undecided")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Undecided")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Undecided")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Undecided")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Undecided")
UndecidedReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Persuadable Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Persuadable) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Persuadable)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Persuadable)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Persuadable)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Persuadable) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Persuadable) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Persuadable) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Persuadable)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Persuadable) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Persuadable)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Persuadable")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Persuadable")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Persuadable")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Persuadable")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Persuadable")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Persuadable")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Persuadable")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Persuadable")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Persuadable")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Persuadable")
PersuadableReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Primary Ideo Regressions
##Very Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = VeryCons) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = VeryCons)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = VeryCons)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = VeryCons)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = VeryCons) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = VeryCons) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = VeryCons) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = VeryCons)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = VeryCons) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = VeryCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("VeryCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("VeryCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("VeryCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("VeryCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("VeryCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("VeryCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("VeryCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("VeryCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("VeryCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("VeryCons")
VeryConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Somewhat Cons Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = SmwtCons) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = SmwtCons)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = SmwtCons)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = SmwtCons)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = SmwtCons) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = SmwtCons) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = SmwtCons) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = SmwtCons)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = SmwtCons) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = SmwtCons)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SmwtCons")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SmwtCons")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SmwtCons")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SmwtCons")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SmwtCons")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SmwtCons")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SmwtCons")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SmwtCons")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SmwtCons")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SmwtCons")
SmwtConsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Mod/Lib Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = ModLib) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = ModLib)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = ModLib)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = ModLib)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = ModLib) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = ModLib) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = ModLib) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = ModLib)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = ModLib) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = ModLib)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("ModLib")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("ModLib")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("ModLib")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("ModLib")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("ModLib")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("ModLib")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("ModLib")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("ModLib")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("ModLib")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("ModLib")
ModLibReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Stated Party Regressions
##Republican Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Republican) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Republican)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Republican)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Republican)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Republican) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Republican) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Republican) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Republican)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Republican) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Republican)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Republican")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Republican")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Republican")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Republican")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Republican")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Republican")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Republican")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Republican")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Republican")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Republican")
RepublicanReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Independent Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Independent) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Independent)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Independent)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Independent)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Independent) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Independent) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Independent) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Independent)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Independent) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Independent)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Independent")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Independent")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Independent")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Independent")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Independent")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Independent")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Independent")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Independent")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Independent")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Independent")
IndependentReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Democrat Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Democrat) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Democrat)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Democrat)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Democrat)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Democrat) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Democrat) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Democrat) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Democrat)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Democrat) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Democrat)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Democrat")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Democrat")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Democrat")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Democrat")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Democrat")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Democrat")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Democrat")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Democrat")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Democrat")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Democrat")
DemocratReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Region Regressions
##Potter Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Potter) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Potter)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Potter)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Potter)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Potter) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Potter) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Potter) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Potter)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Potter) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Potter)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Potter")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Potter")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Potter")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Potter")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Potter")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Potter")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Potter")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Potter")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Potter")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Potter")
PotterReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Randall Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = Randall) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = Randall)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = Randall)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = Randall)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = Randall) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = Randall) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = Randall) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = Randall)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = Randall) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = Randall)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Randall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Randall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Randall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Randall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Randall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Randall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Randall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Randall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Randall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Randall")
RandallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Project Specific Regressions
##Sixty Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = SixtyMil) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = SixtyMil)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = SixtyMil)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = SixtyMil)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = SixtyMil) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = SixtyMil) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = SixtyMil) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = SixtyMil)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = SixtyMil) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = SixtyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SixtyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SixtyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SixtyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SixtyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SixtyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SixtyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SixtyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SixtyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SixtyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SixtyMil")
SixtyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Seventy five Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = SevenFiveMil) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = SevenFiveMil)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = SevenFiveMil)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = SevenFiveMil)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = SevenFiveMil) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = SevenFiveMil) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = SevenFiveMil) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = SevenFiveMil)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = SevenFiveMil) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = SevenFiveMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("SevenFiveMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("SevenFiveMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("SevenFiveMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("SevenFiveMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("SevenFiveMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("SevenFiveMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("SevenFiveMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("SevenFiveMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("SevenFiveMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("SevenFiveMil")
SevenFiveMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ninety Million Sample Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = NinteyMil) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = NinteyMil)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = NinteyMil)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = NinteyMil)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = NinteyMil) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = NinteyMil) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = NinteyMil) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = NinteyMil)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = NinteyMil) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = NinteyMil)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NinteyMil")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NinteyMil")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NinteyMil")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NinteyMil")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NinteyMil")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NinteyMil")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NinteyMil")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NinteyMil")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NinteyMil")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NinteyMil")
NinteyMilReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Has Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = HasKids) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = HasKids)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = HasKids)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = HasKids)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = HasKids) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = HasKids) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = HasKids) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = HasKids)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = HasKids) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = HasKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("HasKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("HasKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("HasKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("HasKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("HasKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("HasKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("HasKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("HasKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("HasKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("HasKids")
HasKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##No Kids Regression with Weight
fit1 <- lm(Change ~ HRD_CAND1_POS_1, weights = Weight, data = NoKids) 
fit2 <- lm(Change ~ HRD_CAND1_POS_2, weights = Weight, data = NoKids)
fit3 <- lm(Change ~ HRD_CAND1_POS_3, weights = Weight, data = NoKids)
fit4 <- lm(Change ~ HRD_CAND1_POS_4, weights = Weight, data = NoKids)
fit5 <- lm(Change ~ HRD_CAND1_POS_5, weights = Weight, data = NoKids) 
fit6 <- lm(Change ~ HRD_CAND1_POS_6, weights = Weight, data = NoKids) 
fit7 <- lm(Change ~ HRD_CAND1_POS_7, weights = Weight, data = NoKids) 
fit8 <- lm(Change ~ HRD_CAND1_POS_8, weights = Weight, data = NoKids)
fit9 <- lm(Change ~ HRD_CAND1_POS_9, weights = Weight, data = NoKids) 
fit10 <- lm(Change ~ HRD_CAND1_POS_10, weights = Weight, data = NoKids)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NoKids")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NoKids")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NoKids")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NoKids")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NoKids")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NoKids")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NoKids")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NoKids")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NoKids")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NoKids")
NoKidsReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

Cand1PosReg <- cbind(OverallReg, UndecidedReg, PersuadableReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, ConservativeReg, VeryConsReg, SmwtConsReg, ModerateReg, LiberalReg, ModLibReg, RepublicanReg, IndependentReg, DemocratReg, PotterReg, RandallReg, SixtyMilReg, SevenFiveMilReg, NinteyMil, HasKidsReg, NoKidsReg)
write.csv(Cand1PosReg, file ="Cand1PosReg.csv")
##Possibly combine into one excel file with:
write.xlsx(Cand1PosReg, file ="Region_Race.xlsx", sheetName = "Cand1PosReg", append = TRUE)
```
