
```{r}
##Package installs
install.packages("xlsx")
install.packages("rJava")
install.packages("xlsxjars")
library(xlsx)
library(rJava)
library(xlsxjars)
```

```{r}
##Variable codes
Data <- Austin_TX_n400_2_
##Ballot Recode
NeverHeardOf <- Data [ which(Data$Q_IMAGE_PERSONINITIALS_PE == 4), ]
##Gender
Men <- Data [ which(Data$R_GENDER == 1), ]
Women <- Data [ which(Data$R_GENDER == 2), ]
##Age
Age1844 <- Data [ which(Data$R_AGE == 1), ]
Age4564 <- Data [ which(Data$R_AGE == 2), ]
Age65 <- Data [ which(Data$R_AGE == 3), ]
##Gender x Age
Men1844 <- Data [ which(Data$R_GENAGE == 1), ]
Men4564 <- Data [ which(Data$R_GENAGE == 2), ]
Men65 <- Data [ which(Data$R_GENAGE == 3), ]
Women1844 <- Data [ which(Data$R_GENAGE == 4), ]
Women4564 <- Data [ which(Data$R_GENAGE == 5), ]
Women65 <- Data [ which(Data$R_GENAGE == 6), ]
##Race/Ethnicity
White <- Data [ which(Data$R_ETHNICITY == 1), ]
Hispanic <- Data [ which(Data$R_ETHNICITY == 2), ]
##General Ideo
Conservative <- Data [ which(Data$R_Ideology == 1), ]
Moderate <- Data [ which(Data$R_Ideology == 2), ]
Liberal <- Data [ which(Data$R_Ideology == 3), ]
##Region
Central <- Data [ which(Data$R_REGION == 1), ]
East <- Data [ which(Data$R_REGION == 2), ]
South <- Data [ which(Data$R_REGION == 3), ]
West <- Data [ which(Data$R_REGION == 4), ]

```

```{r}
#Ballot Recode and Changes
Austin_TX_n400_2_$ImageRecode <-
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 1, 1, 
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 2, 2, 
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 3, 4,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 4, 3,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 5, 5,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PERSONINITIALS_PE == 6, 6, 0))))))

Austin_TX_n400_2_$ImageRecode2 <-
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 1, 1, 
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 2, 2, 
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 3, 4,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 4, 3,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 5, 5,
      ifelse(Austin_TX_n400_2_$Q_IMAGE_PE_INF == 6, 6, 0))))))
```

```{r}
##Change/Changes
##computing Change Variables
Austin_TX_n400_2_$Change <- (Austin_TX_n400_2_$ImageRecode2 - Austin_TX_n400_2_$ImageRecode)

```

```{r}
##Client Positive Messaging
##Topline Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Data) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Data)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Data)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Data)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Data) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Data) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Data) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Data)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Data) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Data)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Overall")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Overall")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Overall")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Overall")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Overall")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Overall")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Overall")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Overall")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Overall")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Overall")
OverallReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Ballot Regressions
##Never Heard of PE Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = NeverHeardOf) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = NeverHeardOf)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = NeverHeardOf)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = NeverHeardOf)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = NeverHeardOf) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = NeverHeardOf) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = NeverHeardOf) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = NeverHeardOf)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = NeverHeardOf) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = NeverHeardOf)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("NeverHeardOf")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("NeverHeardOf")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("NeverHeardOf")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("NeverHeardOf")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("NeverHeardOf")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("NeverHeardOf")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("NeverHeardOf")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("NeverHeardOf")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("NeverHeardOf")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("NeverHeardOf")
NeverHeardOfReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender Regressions
##Men Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Men) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Men)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Men)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Men)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Men) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Men) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Men) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Men)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Men) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Men)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men")
MenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Women) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Women)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Women)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Women)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Women) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Women) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Women) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Women)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Women) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Women)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women")
WomenReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age Regressions
##Age1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Age1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Age1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Age1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Age1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Age1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Age1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Age1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Age1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Age1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Age1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age1844")
Age1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Age4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Age4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Age4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Age4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Age4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Age4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Age4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Age4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Age4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Age4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age4564")
Age4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Age65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Age65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Age65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Age65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Age65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Age65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Age65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Age65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Age65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Age65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Age65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Age65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Age65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Age65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Age65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Age65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Age65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Age65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Age65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Age65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Age65")
Age65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Gender x Age Regressions
##Men1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Men1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Men1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Men1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Men1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Men1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Men1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Men1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Men1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Men1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Men1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men1844")
Men1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Men4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Men4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Men4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Men4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Men4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Men4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Men4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Men4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Men4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Men4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men4564")
Men4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Men65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Men65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Men65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Men65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Men65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Men65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Men65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Men65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Men65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Men65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Men65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Men65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Men65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Men65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Men65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Men65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Men65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Men65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Men65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Men65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Men65")
Men65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women1844 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Women1844) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Women1844)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Women1844)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Women1844)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Women1844) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Women1844) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Women1844) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Women1844)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Women1844) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Women1844)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women1844")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women1844")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women1844")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women1844")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women1844")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women1844")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women1844")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women1844")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women1844")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women1844")
Women1844Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women4564 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Women4564) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Women4564)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Women4564)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Women4564)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Women4564) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Women4564) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Women4564) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Women4564)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Women4564) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Women4564)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women4564")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women4564")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women4564")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women4564")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women4564")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women4564")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women4564")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women4564")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women4564")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women4564")
Women4564Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Women65 Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Women65) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Women65)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Women65)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Women65)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Women65) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Women65) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Women65) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Women65)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Women65) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Women65)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Women65")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Women65")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Women65")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Women65")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Women65")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Women65")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Women65")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Women65")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Women65")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Women65")
Women65Reg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Race/Ethnicity Regressions
##White Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = White) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = White)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = White)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = White)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = White) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = White) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = White) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = White)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = White) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = White)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("White")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("White")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("White")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("White")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("White")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("White")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("White")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("White")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("White")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("White")
WhiteReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Hispanic Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Hispanic) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Hispanic)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Hispanic)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Hispanic)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Hispanic) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Hispanic) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Hispanic) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Hispanic)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Hispanic) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Hispanic)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Hispanic")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Hispanic")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Hispanic")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Hispanic")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Hispanic")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Hispanic")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Hispanic")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Hispanic")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Hispanic")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Hispanic")
HispanicReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##General Ideo Regressions
##Conservative Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Conservative) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Conservative)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Conservative)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Conservative)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Conservative) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Conservative) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Conservative) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Conservative)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Conservative) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Conservative)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Conservative")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Conservative")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Conservative")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Conservative")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Conservative")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Conservative")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Conservative")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Conservative")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Conservative")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Conservative")
ConservativeReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Moderate Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Moderate) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Moderate)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Moderate)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Moderate)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Moderate) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Moderate) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Moderate) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Moderate)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Moderate) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Moderate)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Moderate")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Moderate")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Moderate")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Moderate")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Moderate")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Moderate")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Moderate")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Moderate")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Moderate")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Moderate")
ModerateReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##Liberal Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Liberal) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Liberal)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Liberal)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Liberal)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Liberal) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Liberal) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Liberal) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Liberal)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Liberal) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Liberal)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Liberal")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Liberal")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Liberal")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Liberal")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Liberal")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Liberal")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Liberal")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Liberal")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Liberal")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Liberal")
LiberalReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

#Region Regressions
##Central Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = Central) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = Central)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = Central)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = Central)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = Central) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = Central) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = Central) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = Central)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = Central) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = Central)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("Central")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("Central")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("Central")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("Central")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("Central")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("Central")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("Central")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("Central")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("Central")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("Central")
CentralReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##East Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = East) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = East)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = East)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = East)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = East) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = East) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = East) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = East)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = East) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = East)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("East")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("East")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("East")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("East")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("East")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("East")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("East")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("East")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("East")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("East")
EastReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##South Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = South) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = South)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = South)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = South)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = South) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = South) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = South) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = South)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = South) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = South)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("South")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("South")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("South")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("South")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("South")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("South")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("South")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("South")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("South")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("South")
SouthReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)

##West Regression with Weight
fit1 <- lm(Change ~ HRD_CLIENT_POS_15, weights = Weight, data = West) 
fit2 <- lm(Change ~ HRD_CLIENT_POS_16, weights = Weight, data = West)
fit3 <- lm(Change ~ HRD_CLIENT_POS_17, weights = Weight, data = West)
fit4 <- lm(Change ~ HRD_CLIENT_POS_18, weights = Weight, data = West)
fit5 <- lm(Change ~ HRD_CLIENT_POS_19, weights = Weight, data = West) 
fit6 <- lm(Change ~ HRD_CLIENT_POS_20, weights = Weight, data = West) 
fit7 <- lm(Change ~ HRD_CLIENT_POS_21, weights = Weight, data = West) 
fit8 <- lm(Change ~ HRD_CLIENT_POS_22, weights = Weight, data = West)
fit9 <- lm(Change ~ HRD_CLIENT_POS_23, weights = Weight, data = West) 
fit10 <- lm(Change ~ HRD_CLIENT_POS_24, weights = Weight, data = West)
B1 <- data.frame(coefficients(fit1))
colnames(B1) <- ("West")
B2 <- data.frame(coefficients(fit2))
colnames(B2) <- ("West")
B3 <- data.frame(coefficients(fit3))
colnames(B3) <- ("West")
B4 <- data.frame(coefficients(fit4))
colnames(B4) <- ("West")
B5 <- data.frame(coefficients(fit5))
colnames(B5) <- ("West")
B6 <- data.frame(coefficients(fit6))
colnames(B6) <- ("West")
B7 <- data.frame(coefficients(fit7))
colnames(B7) <- ("West")
B8 <- data.frame(coefficients(fit8))
colnames(B8) <- ("West")
B9 <- data.frame(coefficients(fit9))
colnames(B9) <- ("West")
B10 <- data.frame(coefficients(fit10))
colnames(B10) <- ("West")
WestReg <- rbind(B1,B2,B3,B4,B5,B6,B7,B8,B9,B10)


ClientPosReg <- cbind(OverallReg, NeverHeardOfReg, MenReg, WomenReg, Age1844Reg, Age4564Reg, Age65Reg, Men1844Reg, Men4564Reg, Men65Reg, Women1844Reg, Women4564Reg, Women65Reg, WhiteReg, HispanicReg, ConservativeReg, ModerateReg, LiberalReg, CentralReg, EastReg, SouthReg, WestReg)
write.csv(ClientPosReg, file ="ClientPosReg.csv")
##Possibly combine into one excel file with:
write.xlsx(ClientPosReg, file ="Austin_Parsley.xlsx", sheetName = "ClientPosReg", append = FALSE)
```

